### PR TITLE
*southern voice* You been writin' too much Python, boy?

### PR DESCRIPTION
**Pull request by Ironholds**
Spaces around equals signs. Also stop_on_status calls to simplify the wackery that is trying to retrieve content from a failed request.

### CODE REVIEW

**Comment by hrbrmstr** [comment]
I reject spaces around equals patches ;-)

**Comment by hrbrmstr** [comment]
agreed abt `stop_on_status` tho. i cranked this out whilst trying to recover from the SO's of two daughters notifying me this week they're going to propose. that, coupled with my mom falling and breaking her _other_ arm (in Delaware) and extremely sick hound has made me somewhat anti-social this week.

**Comment by Ironholds** [comment]
Aw, I'm sorry to hear allothat dude :(. I hope your mom feels better soon!

**Comment by hrbrmstr** [comment]
i think we can make a similar API service for SSL certs grabbed by sonar, btw. can't do the in-depth, active testing (well, mebbe we can). i need to see if the sonar web interface supports cert queries

**Comment by Ironholds** [comment]
OOh. Let's do it. I'm a big fan of having APIs where I get to specify the format. Means better-written API formats. And DS is looking for more work right now, so you should start a thread!

**Pull request merged**
